# Generated by Django 2.0 on 2021-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_t_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_dict',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='category',
            field=models.CharField(choices=[('country', 'Country'), ('header', 'Header')], default='', max_length=20),
        ),
    ]
