# Generated by Django 2.0 on 2021-01-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_auto_20210113_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='province',
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='category',
            field=models.CharField(choices=[('Country', 'Country'), ('Header', 'Header')], default='', max_length=20),
        ),
    ]
